export enum EventPermission {
  EVENT_CREATE = 'EVENT_CREATE',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_DELETE = 'EVENT_DELETE',
  CFP_MANAGE = 'CFP_MANAGE',
  REVIEW_ASSIGN = 'REVIEW_ASSIGN',
  REVIEW_SUBMIT = 'REVIEW_SUBMIT',
  PROPOSAL_SUBMIT = 'PROPOSAL_SUBMIT',
  PROPOSAL_EDIT = 'PROPOSAL_EDIT',
  PROPOSAL_WITHDRAW = 'PROPOSAL_WITHDRAW',
}
