export enum OrganizationPermission {
  ORGANIZATION_READ = 'ORGANIZATION_READ',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  ORGANIZATION_DELETE = 'ORGANIZATION_DELETE',
  ORGANIZATION_ARCHIVE = 'ORGANIZATION_ARCHIVE',
  ORGANIZATION_RESTORE = 'ORGANIZATION_RESTORE',
  MEMBER_INVITE = 'MEMBER_INVITE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
}
