export enum Permission {
  ORGANIZATION_READ = 'ORGANIZATION_READ',
  ORGANIZATION_MANAGE = 'ORGANIZATION_MANAGE',
  EVENT_CREATE = 'EVENT_CREATE',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_DELETE = 'EVENT_DELETE',
  PROPOSAL_SUBMIT = 'PROPOSAL_SUBMIT',
  REVIEW_ASSIGN = 'REVIEW_ASSIGN',
  REVIEW_SUBMIT = 'REVIEW_SUBMIT',
}
