export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORGANIZATION_OWNER = 'ORGANIZATION_OWNER',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  PROGRAM_CHAIR = 'PROGRAM_CHAIR',
  REVIEWER = 'REVIEWER',
  SPEAKER = 'SPEAKER',
}
