export enum OrganizationPermission {
  ORGANIZATION_READ = 'ORGANIZATION_READ',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  MEMBERSHIP_READ = 'MEMBERSHIP_READ',
  INVITATION_CREATE = 'INVITATION_CREATE',
  OWNERSHIP_TRANSFER = 'OWNERSHIP_TRANSFER',
}
