export type DiagnosticErrorCode =
  | 'CONFIG_INVALID'
  | 'EMULATOR_CONFIG_FORBIDDEN'
  | 'PROFILE_DOCUMENT_INVALID'
  | 'PROFILE_IDENTITY_MISMATCH'
  | 'PROFILE_PARTIAL_WRITE_UNSUPPORTED'
  | 'ORGANIZATION_PARTIAL_WRITE_UNSUPPORTED'
  | 'ORGANIZATION_STORAGE_INVARIANT_FAILED'
  | 'AUDIT_ACTOR_MISMATCH';
