export enum EventPermission {
  CFP_MANAGE = 'CFP_MANAGE',

  EVENT_READ = 'EVENT_READ',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_ARCHIVE = 'EVENT_ARCHIVE',
  EVENT_PUBLISH = 'EVENT_PUBLISH',
  EVENT_MEMBER_READ = 'EVENT_MEMBER_READ',
  EVENT_MEMBER_MANAGE = 'EVENT_MEMBER_MANAGE',

  REVIEW_ASSIGN = 'REVIEW_ASSIGN',
  REVIEW_SUBMIT = 'REVIEW_SUBMIT',
}
