export enum EventPermission {
  CFP_MANAGE = 'CFP_MANAGE',

  EVENT_READ = 'EVENT_READ',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_ARCHIVE = 'EVENT_ARCHIVE',
  EVENT_PUBLISH = 'EVENT_PUBLISH',
  EVENT_MEMBER_READ = 'EVENT_MEMBER_READ',
  EVENT_MEMBER_MANAGE = 'EVENT_MEMBER_MANAGE',

  REVIEW_ASSIGN = 'REVIEW_ASSIGN',
  REVIEW_SUBMIT = 'REVIEW_SUBMIT',

  RUBRIC_MANAGE = 'RUBRIC_MANAGE',
  REVIEW_PERIOD_MANAGE = 'REVIEW_PERIOD_MANAGE',
  REVIEW_READ_ALL = 'REVIEW_READ_ALL',
  REVIEWER_QUEUE_READ = 'REVIEWER_QUEUE_READ',
  CONFLICT_DECLARE = 'CONFLICT_DECLARE',
  CONFLICT_MANAGE = 'CONFLICT_MANAGE',

  REVIEW_SCORECARD_READ = 'REVIEW_SCORECARD_READ',
  REVIEW_COVERAGE_READ = 'REVIEW_COVERAGE_READ',
  PROPOSAL_IDENTITY_READ = 'PROPOSAL_IDENTITY_READ',

  DECISION_ROUND_MANAGE = 'DECISION_ROUND_MANAGE',
  PROPOSAL_DECISION_MANAGE = 'PROPOSAL_DECISION_MANAGE',
  DECISION_READ = 'DECISION_READ',
}
