export enum OrganizationPermission {
  MEMBER_READ = 'MEMBER_READ',
  MEMBER_INVITE = 'MEMBER_INVITE',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  ORGANIZATION_READ = 'ORGANIZATION_READ',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  ORGANIZATION_ARCHIVE = 'ORGANIZATION_ARCHIVE',
  ORGANIZATION_RESTORE = 'ORGANIZATION_RESTORE',
  ORGANIZATION_TRANSFER_OWNERSHIP = 'ORGANIZATION_TRANSFER_OWNERSHIP',

  EVENT_CREATE = 'EVENT_CREATE',
}
