export type AuthenticationErrorCode =
  | 'AUTH_REQUIRED'
  | 'AUTH_INVALID_TOKEN'
  | 'AUTH_TOKEN_EXPIRED'
  | 'AUTH_TOKEN_REVOKED'
  | 'AUTH_USER_DISABLED'
  | 'EMAIL_VERIFICATION_REQUIRED'
  | 'AUTH_UNAVAILABLE';
